name: Go Build and Release (Cross-platform)

on:
  push:
    tags:
      - v*  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Платформы
        arch: [amd64, arm64]  # Архитектуры

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.25.4'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Build Go Application (Cross-Platform)
      run: |
        case "${{ matrix.os }}" in
          "ubuntu-latest")
            GOOS=linux
            ext=""
            ;;
          "windows-latest")
            GOOS=windows
            ext=".exe"
            ;;
          "macos-latest")
            GOOS=darwin
            ext=""
            ;;
          *)
            echo "Unknown OS: ${{ matrix.os }}" >&2
            exit 1
            ;;
        esac
        GOARCH=${{ matrix.arch }}
        output="Arma-Reforger-api-${{ matrix.os }}-${GOARCH}${ext}"
        GOOS=$GOOS GOARCH=$GOARCH go build -o "$output"
    - name: Package the build into a ZIP archive
      run: |
        mkdir -p arma-reforger-api
        cp Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}* arma-reforger-api/
        cp config.json arma-reforger-api/
        zip -r Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}.zip arma-reforger-api/
    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}
        path: Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}.zip
      

